### PR TITLE
This modification will make AA work with WorldGuard as well as other plugin processing BlockBreakEvent.

### PR DESCRIPTION
**Pull request by vk2gpz**
This modification will make AA work with WorldGuard as well as other plugin processing BlockBreakEvent.

### CODE REVIEW

**Review by PyvesB — CHANGES_REQUESTED** [review]
Hello @vk2gpz ! :wave:

On the contrary, this breaks World Guard and other plugind as blocks that are protected and can't be broken will now potentially count towards _Breaks_ events. Bukkit API guidance should be followed and event priorities should not be tampered with, see https://github.com/PyvesB/advanced-achievements/issues/985#issuecomment-806503987 for more details. 😉

**Comment by vk2gpz** [comment]
> Hello @vk2gpz ! 👋
> 
> On the contrary, this breaks World Guard and other plugind as blocks that are protected and can't be broken will now potentially count towards _Breaks_ events. Bukkit API guidance should be followed and event priorities should not be tampered with, see [#985 (comment)](https://github.com/PyvesB/advanced-achievements/issues/985#issuecomment-806503987) for more details. 😉

this is the fix for that issue.  I applied this patch and the user who reported #985 now having no issue.
If you do not want to apply this fix, that's fine, you can just discard it.

**Comment by PyvesB** [comment]
This is very much not a fix given that it leads to violations of the Spigot API contracts and introduces other bugs. Your plugin improperly uses the API, that's what needs fixing - I've taken time to outline what needs to be done on your side in the linked message, please consider that rather than trying to impose faulty workarounds in every single plugin that is listening to _BlockBreakEvents_ in an API-compliant manner.

**Comment by vk2gpz** [comment]
> This is very much not a fix given that it leads to violations of the Spigot API contracts and introduces other bugs. Your plugin improperly uses the API, that's what needs fixing - I've taken time to outline what needs to be done on your side in the linked message, please consider that rather than trying to impose faulty workarounds in every single plugin that is listening to _BlockBreakEvents_ in an API-compliant manner.

this is why I said, you completely misunderstood.  If you're listing event only at MONITOR, that will completely blocks plugins which needs to process BlockBreakEvent after you plugin.

Well, it's not my problem and the user who reported issue is now fine with the fix.

Please just ignore this PR.

**Comment by PyvesB** [comment]
You're contradicting the API documentation and seem to have ignored all the references I kindly provided in the linked issue, this suggests I am not the one who is misunderstanding here. In addition to being condescending, barging in on someone else's project and lecturing them on how they "completely misunderstand" their domain makes up for quite a ridicule impression when the lecturer turns out to be the one in the wrong.

More generally, I'm not impressed with the attitude here: no attempt to engage on the issue beforehand, not a single mark of courtesy, condescending tone, messages written hastily and edited up to half a dozen times, multiple typos, advocating for a solution (i.e. configurability) which is precisely not what your PR is achieving, etc. I'm really unsure what your goal was here, but it clearly doesn't feel very constructive, so will go ahead and lock.

**Pull request closed without merging**
